NoorEl7abeebCompanyWebApp/Controllers/ExportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NoorEl7abeebCompanyWebApp.Models;
using NoorEl7abeebCompanyWebApp.Models.MyModels;

namespace NoorEl7abeebCompanyWebApp.Controllers
{
    [Authorize]
    public class ExportsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Exports
        public async Task<ActionResult> Index()
        {
            var exports = db.Exports.Include(e => e.BoxType).Include(e => e.Customer);
            return View(await exports.ToListAsync());
        }

        // GET: Exports/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Export export = await db.Exports.FindAsync(id);
            if (export == null)
            {
                return HttpNotFound();
            }
            return View(export);
        }

        // GET: Exports/Create
        public ActionResult Create(int? customerId)
        {
            if (customerId != null)
            {
                var customer = db.Customers.SingleOrDefault(i => i.Id == customerId);
                if (customer == null)
                {
                    return HttpNotFound();
                }
                ViewBag.CustomerId = customerId;
                ViewBag.CustomerName = customer.Name;
            }
            else
            {
                ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name");
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name");
            return View();
        }

        // POST: Exports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Date,Quantity,Notes,CustomerId,BoxTypeId")] Export export)
        {
            if (ModelState.IsValid)
            {
                db.Exports.Add(export);
                var c = db.Customers.Find(export.CustomerId);
                var rest = c.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == export.BoxTypeId);
                if (rest != null)
                {
                    rest.Count += export.Quantity;
                }
                else
                {
                    db.RestBoxeses.Add(new RestBoxes
                    {
                        CustomerId = export.CustomerId,
                        BoxTypeId = export.BoxTypeId,
                        Count = export.Quantity
                    });
                }
                await db.SaveChangesAsync();
                if (Request.IsAjaxRequest())
                { 
                    var result = new { Quantity = export.Quantity, BoxType = db.BoxTypes.Find(export.BoxTypeId).Name, Customer = c.Name };
                    return Json(result,JsonRequestBehavior.AllowGet);
                }
                return RedirectToAction("Index");
            }

            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", export.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", export.CustomerId);
            return View(export);
        }

        public ActionResult ReturnEmptyBoxes(int? customerId)
        {
            if (customerId != null)
            {
                var customer = db.Customers.SingleOrDefault(i => i.Id == customerId);
                if (customer == null)
                {
                    return HttpNotFound();
                }
                ViewBag.CustomerId = customerId;
                ViewBag.CustomerName = customer.Name;
            }
            else
            {
                ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name");
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ReturnEmptyBoxes([Bind(Include = "Id,Count,CustomerId,BoxTypeId")] RestBoxes restBoxes)
        {
            if (ModelState.IsValid)
            {
                var c = db.Customers.Find(restBoxes.CustomerId);
                var rest = c.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == restBoxes.BoxTypeId);
                if (rest != null)
                {
                    rest.Count -= restBoxes.Count;
                }
                else
                {
                    restBoxes.Count *= -1;
                    db.RestBoxeses.Add(restBoxes);
                }
                db.Exports.Add(new Export
                {
                    BoxTypeId = restBoxes.BoxTypeId,
                    CustomerId = restBoxes.CustomerId,
                    Date = DateTime.Now,
                    Quantity = restBoxes.Count<0?restBoxes.Count:(restBoxes.Count*-1)
                });
                await db.SaveChangesAsync();
                if (Request.IsAjaxRequest())
                {
                    var result = new { Quantity = restBoxes.Count, BoxType = db.BoxTypes.Find(restBoxes.BoxTypeId).Name, Customer = c.Name };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                return RedirectToAction("Index");
            }

            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", restBoxes.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", restBoxes.CustomerId);
            return View(restBoxes);
        }
        
        // GET: Exports/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Export export = await db.Exports.FindAsync(id);
            if (export == null)
            {
                return HttpNotFound();
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", export.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", export.CustomerId);
            return View(export);
        }

        // POST: Exports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Date,Quantity,Notes,CustomerId,BoxTypeId")] Export export)
        {
            if (ModelState.IsValid)
            {
                var exportInDbQuantity = db.Exports.Find(export.Id).Quantity;
                db.Entry(export).State = EntityState.Modified;
                var c = db.Customers.Find(export.CustomerId);
                var rest = c.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == export.BoxTypeId);
                if (rest != null)
                {
                    rest.Count -= exportInDbQuantity;
                    rest.Count += export.Quantity;
                }
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", export.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", export.CustomerId);
            return View(export);
        }

        // GET: Exports/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Export export = await db.Exports.FindAsync(id);
            if (export == null)
            {
                return HttpNotFound();
            }
            return View(export);
        }

        // POST: Exports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Export export = await db.Exports.FindAsync(id);
            var rest = export.Customer.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == export.BoxTypeId);
            if (rest != null)
            {
                rest.Count -= export.Quantity;
            }
            db.Exports.Remove(export);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult RestBoxesForPeriod()
        {
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RestBoxesForPeriod(int BoxTypeId)
        {
            var box = db.BoxTypes.Include(b => b.Imports).FirstOrDefault(b => b.Id == BoxTypeId);
            List<RestBoxes> result;
            if (box != null)
            {
                result = box.RestBoxeses.ToList();
            }
            else
            {
                result = db.RestBoxeses.ToList();
            }
            return PartialView("_RestBoxes", result);
        }
    }
}

NoorEl7abeebCompanyWebApp/Controllers/ImportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NoorEl7abeebCompanyWebApp.Models;
using NoorEl7abeebCompanyWebApp.Models.MyModels;

namespace NoorEl7abeebCompanyWebApp.Controllers
{
    [Authorize]
    public class ImportsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Imports
        public async Task<ActionResult> Index()
        {
            var imports = db.Imports.Include(i => i.BoxType).Include(i => i.Customer);
            return View(await imports.ToListAsync());
        }

        // GET: Imports/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Import import = await db.Imports.FindAsync(id);
            if (import == null)
            {
                return HttpNotFound();
            }
            return View(import);
        }

        // GET: Imports/Create
        public ActionResult Create(int? customerId)
        {
            if (customerId != null)
            {
                var customer = db.Customers.SingleOrDefault(i => i.Id == customerId);
                if (customer == null)
                {
                    return HttpNotFound();
                }
                ViewBag.CustomerId = customerId;
                ViewBag.CustomerName = customer.Name;
            }
            else
            {
                ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name");
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name");
            return View();
        }

        // POST: Imports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Date,Quantity,Weight,Price,Notes,CustomerId,BoxTypeId")] Import import)
        {
            import.TotalWeight = import.Weight * import.Quantity;
            import.TotalPrice = import.Price * import.TotalWeight;

            if (ModelState.IsValid)
            {
                db.Imports.Add(import);
                var c = db.Customers.Find(import.CustomerId);
                var rest = c.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == import.BoxTypeId);
                if (rest != null)
                {
                    rest.Count -= import.Quantity;
                }
                else
                {
                    db.RestBoxeses.Add(new RestBoxes
                    {
                        CustomerId = import.CustomerId,
                        BoxTypeId = import.BoxTypeId,
                        Count = (import.Quantity * (-1))
                    });
                }
                await db.SaveChangesAsync();
                if (Request.IsAjaxRequest())
                {
                    var result = new { Quantity = import.Quantity, BoxType = db.BoxTypes.Find(import.BoxTypeId).Name, Customer = c.Name };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                return RedirectToAction("Index");
            }

            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", import.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", import.CustomerId);
            return View(import);
        }
        // GET: Imports/ReturnEmptyBoxes
        

        // GET: Imports/Edit/5
            public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Import import = await db.Imports.FindAsync(id);
            if (import == null)
            {
                return HttpNotFound();
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", import.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", import.CustomerId);
            return View(import);
        }

        // POST: Imports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Date,Quantity,Weight,Price,Notes,CustomerId,BoxTypeId")] Import import)
        {
            import.TotalWeight = import.Weight * import.Quantity;
            import.TotalPrice = import.Price * import.TotalWeight;
            if (ModelState.IsValid)
            {
                var importInDbQuantity = db.Imports.Find(import.Id).Quantity;
                db.Entry(import).State = EntityState.Modified;
                var c = db.Customers.Find(import.CustomerId);
                var rest = c.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == import.BoxTypeId);
                if (rest != null)
                {
                    rest.Count += importInDbQuantity;
                    rest.Count -= import.Quantity;
                }
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", import.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", import.CustomerId);
            return View(import);
        }

        // GET: Imports/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Import import = await db.Imports.FindAsync(id);
            if (import == null)
            {
                return HttpNotFound();
            }
            return View(import);
        }

        // POST: Imports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Import import = await db.Imports.FindAsync(id);
            var rest=import.Customer.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == import.BoxTypeId);
            if (rest != null)
            {
                rest.Count += import.Quantity;
            }
            db.Imports.Remove(import);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ImportsForPeriod()
        {
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ImportsForPeriod(Period period)
        {
            var box = db.BoxTypes.Include(b=>b.Imports).FirstOrDefault(b=>b.Id==period.BoxTypeId);
            List<Import> result;
            if (box != null)
            {
                result = box.Imports.Where(i =>
                 i.Date.CompareTo(period.From) >= 0
                && i.Date.CompareTo(period.To) <= 0
             ).ToList();
            }
            else
            {
                result = db.Imports.Where(i =>
                 i.Date.CompareTo(period.From) >= 0
                && i.Date.CompareTo(period.To) <= 0
             ).ToList();
            }
            return PartialView("_CustomerImports",result);
        }
    }
}

NoorEl7abeebCompanyWebApp/Views/Shared/_CustomerExports.cshtml
@model IEnumerable<NoorEl7abeebCompanyWebApp.Models.MyModels.Export>
<table id="customers" class="table table-bordered table-striped">
    <thead >
        <tr style="text-align: right">
            <th>
                @Html.DisplayNameFor(model => model.Customer.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BoxType.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th class="noPrint">
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BoxType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td class="bg-success">
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td class="noPrint">
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                @*<td>
                    @Html.ActionLink("تعديل", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                    @Html.ActionLink("تفاصيل", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("مسح", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>*@
            </tr>
        }
    </tbody>
</table>

NoorEl7abeebCompanyWebApp/Views/Shared/_CustomerImports.cshtml
@model IEnumerable<NoorEl7abeebCompanyWebApp.Models.MyModels.Import>
<table id="customers" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Customer.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BoxType.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalWeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
            <th class="noPrint">
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BoxType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td class="bg-success">
                    @Html.DisplayFor(modelItem => item.TotalWeight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td class="bg-info">
                    @Html.DisplayFor(modelItem => item.TotalPrice)
                </td>
                <td class="noPrint">
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                @*<td>
                    @Html.ActionLink("تفاصيل", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) |
                </td>*@
            </tr>
        }
    </tbody>
</table>

NoorEl7abeebCompanyWebApp/Views/Shared/_CustomerPayments.cshtml
@model IEnumerable<NoorEl7abeebCompanyWebApp.Models.MyModels.Payment>
<table id="customers" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Customer.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Money)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td class="bg-success">
                    @Html.DisplayFor(modelItem => item.Money)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
            </tr>
        }
    </tbody>
</table>

NoorEl7abeebCompanyWebApp/Views/Shared/_CustomerPaymentsReport.cshtml
@model IEnumerable<NoorEl7abeebCompanyWebApp.Models.MyModels.CustomerPaymentsReportVM>
<table id="customers" class="table table-bordered table-striped">
    <thead>
        <tr style="text-align: right">
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaidForHim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RestPaymentsForHim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPayments)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td class="bg-success">
                    @Html.DisplayFor(modelItem => item.PaidForHim)
                </td>
                <td class="bg-danger">
                    @Html.DisplayFor(modelItem => item.RestPaymentsForHim)
                </td>
                <td class="bg-primary">
                    @Html.DisplayFor(modelItem => item.TotalPayments)
                </td>
            </tr>
        }
    </tbody>
</table>

NoorEl7abeebCompanyWebApp/Views/Shared/_Header.cshtml
<header class="main-header">
    <nav style="direction:rtl" class="navbar navbar-static-top">
        <div class="container">
            <div class="navbar-header pull-right">
                <b>@Html.ActionLink("نور الحبيب", "index", "Home", null, new { @class = "navbar-brand" })</b>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                <ul   class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">التقارير <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("الواردات عن فترة", "ImportsForPeriod", "Imports", null, null)</li>
                            <li>@Html.ActionLink("المدفوعات عن فترة", "PaymentsForPeriod", "Payments", null, null)</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("الصناديق الفارغة بالخارج", "RestBoxesForPeriod", "Exports", null, null)</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("حساب العملاء", "CustomersPayments", "Payments", null, null)</li>

                        </ul>
                    </li>
                    <li>@Html.ActionLink("الأصنــاف", "Index", "BoxTypes", null, null)</li>
                    <li>@Html.ActionLink("المدفوعات", "Index", "Payments", null, null)</li>
                    <li>@Html.ActionLink("الصادرات", "Index", "Exports", null, null)</li>
                    <li>@Html.ActionLink("الواردات", "Index", "Imports", null, null)</li>
                    <li>@Html.ActionLink("العمــلاء", "Index", "Customers", null, null)</li>
                </ul>
                
                @Html.Partial("_LoginPartial")
            </div>
            <!-- /.navbar-collapse -->
            <!-- Navbar Right Menu -->
            @*<div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        
                        <!-- Notifications Menu -->
                        <li class="dropdown notifications-menu">
                            <!-- Menu toggle button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-warning">10</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">You have 10 notifications</li>
                                <li>
                                    <!-- Inner Menu: contains the notifications -->
                                    <ul class="menu">
                                        <li>
                                            <!-- start notification -->
                                            <a href="#">
                                                <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                            </a>
                                        </li>
                                        <!-- end notification -->
                                    </ul>
                                </li>
                                <li class="footer"><a href="#">View all</a></li>
                            </ul>
                        </li>
                        <!-- Tasks Menu -->
                        <li class="dropdown tasks-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-flag-o"></i>
                                <span class="label label-danger">9</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">You have 9 tasks</li>
                                <li>
                                    <!-- Inner menu: contains the tasks -->
                                    <ul class="menu">
                                        <li>
                                            <!-- Task item -->
                                            <a href="#">
                                                <!-- Task title and progress text -->
                                                <h3>
                                                    Design some buttons
                                                    <small class="pull-right">20%</small>
                                                </h3>
                                                <!-- The progress bar -->
                                                <div class="progress xs">
                                                    <!-- Change the css width attribute to simulate progress -->
                                                    <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                        <span class="sr-only">20% Complete</span>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                        <!-- end task item -->
                                    </ul>
                                </li>
                                <li class="footer">
                                    <a href="#">View all tasks</a>
                                </li>
                            </ul>
                        </li>
                        <!-- User Account Menu -->
                        @Html.Partial("_LoginPartial")
                    </ul>
                </div>*@
            <!-- /.navbar-custom-menu -->
        </div>
        <!-- /.container-fluid -->
    </nav>
</header>