NoorEl7abeebCompanyWebApp/Models/MyModels/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NoorEl7abeebCompanyWebApp.Models.MyModels
{
    public class Customer
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "من فضلك ادخل اسم العميل")]
        [Display(Name = "أسم العميل")]
        public string Name { get; set; }
        // navigation proparties
        public virtual List<Import> Imports { get; set; }
        public virtual List<Export> Exports { get; set; }
        public virtual List<Payment> Payments { get; set; }
        public virtual List<RestBoxes> RestBoxeses { get; set; }
    }
}

NoorEl7abeebCompanyWebApp/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NoorEl7abeebCompanyWebApp.Models;
using NoorEl7abeebCompanyWebApp.Models.MyModels;

namespace NoorEl7abeebCompanyWebApp.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Customers
        public async Task<ActionResult> Index()
        {
            return View(await db.Customers.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Customer customer = await db.Customers
                .Include(c => c.Imports)
                .Include(c => c.Exports)
                .Include(c => c.Payments)
                .SingleOrDefaultAsync(c=>c.Id==id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                await db.SaveChangesAsync();
                //return RedirectToAction("Index");
                return Json(customer,JsonRequestBehavior.AllowGet);
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = await db.Customers.FindAsync(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = await db.Customers.FindAsync(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Customer customer = await db.Customers.FindAsync(id);
            db.Customers.Remove(customer);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NoorEl7abeebCompanyWebApp/Controllers/ExportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NoorEl7abeebCompanyWebApp.Models;
using NoorEl7abeebCompanyWebApp.Models.MyModels;

namespace NoorEl7abeebCompanyWebApp.Controllers
{
    [Authorize]
    public class ExportsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Exports
        public async Task<ActionResult> Index()
        {
            var exports = db.Exports.Include(e => e.BoxType).Include(e => e.Customer);
            return View(await exports.ToListAsync());
        }

        // GET: Exports/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Export export = await db.Exports.FindAsync(id);
            if (export == null)
            {
                return HttpNotFound();
            }
            return View(export);
        }

        // GET: Exports/Create
        public ActionResult Create(int? customerId)
        {
            if (customerId != null)
            {
                var customer = db.Customers.SingleOrDefault(i => i.Id == customerId);
                if (customer == null)
                {
                    return HttpNotFound();
                }
                ViewBag.CustomerId = customerId;
                ViewBag.CustomerName = customer.Name;
            }
            else
            {
                ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name");
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name");
            return View();
        }

        // POST: Exports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Date,Quantity,Notes,CustomerId,BoxTypeId")] Export export)
        {
            if (ModelState.IsValid)
            {
                db.Exports.Add(export);
                var c = db.Customers.Find(export.CustomerId);
                var rest = c.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == export.BoxTypeId);
                if (rest != null)
                {
                    rest.Count += export.Quantity;
                }
                else
                {
                    db.RestBoxeses.Add(new RestBoxes
                    {
                        CustomerId = export.CustomerId,
                        BoxTypeId = export.BoxTypeId,
                        Count = export.Quantity
                    });
                }
                await db.SaveChangesAsync();
                if (Request.IsAjaxRequest())
                { 
                    var result = new { Quantity = export.Quantity, BoxType = db.BoxTypes.Find(export.BoxTypeId).Name, Customer = c.Name };
                    return Json(result,JsonRequestBehavior.AllowGet);
                }
                return RedirectToAction("Index");
            }

            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", export.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", export.CustomerId);
            return View(export);
        }

        public ActionResult ReturnEmptyBoxes(int? customerId)
        {
            if (customerId != null)
            {
                var customer = db.Customers.SingleOrDefault(i => i.Id == customerId);
                if (customer == null)
                {
                    return HttpNotFound();
                }
                ViewBag.CustomerId = customerId;
                ViewBag.CustomerName = customer.Name;
            }
            else
            {
                ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name");
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ReturnEmptyBoxes([Bind(Include = "Id,Count,CustomerId,BoxTypeId")] RestBoxes restBoxes)
        {
            if (ModelState.IsValid)
            {
                var c = db.Customers.Find(restBoxes.CustomerId);
                var rest = c.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == restBoxes.BoxTypeId);
                if (rest != null)
                {
                    rest.Count -= restBoxes.Count;
                }
                else
                {
                    restBoxes.Count *= -1;
                    db.RestBoxeses.Add(restBoxes);
                }
                db.Exports.Add(new Export
                {
                    BoxTypeId = restBoxes.BoxTypeId,
                    CustomerId = restBoxes.CustomerId,
                    Date = DateTime.Now,
                    Quantity = restBoxes.Count<0?restBoxes.Count:(restBoxes.Count*-1)
                });
                await db.SaveChangesAsync();
                if (Request.IsAjaxRequest())
                {
                    var result = new { Quantity = restBoxes.Count, BoxType = db.BoxTypes.Find(restBoxes.BoxTypeId).Name, Customer = c.Name };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                return RedirectToAction("Index");
            }

            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", restBoxes.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", restBoxes.CustomerId);
            return View(restBoxes);
        }
        
        // GET: Exports/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Export export = await db.Exports.FindAsync(id);
            if (export == null)
            {
                return HttpNotFound();
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", export.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", export.CustomerId);
            return View(export);
        }

        // POST: Exports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Date,Quantity,Notes,CustomerId,BoxTypeId")] Export export)
        {
            if (ModelState.IsValid)
            {
                var exportInDbQuantity = db.Exports.Find(export.Id).Quantity;
                db.Entry(export).State = EntityState.Modified;
                var c = db.Customers.Find(export.CustomerId);
                var rest = c.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == export.BoxTypeId);
                if (rest != null)
                {
                    rest.Count -= exportInDbQuantity;
                    rest.Count += export.Quantity;
                }
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name", export.BoxTypeId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", export.CustomerId);
            return View(export);
        }

        // GET: Exports/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Export export = await db.Exports.FindAsync(id);
            if (export == null)
            {
                return HttpNotFound();
            }
            return View(export);
        }

        // POST: Exports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Export export = await db.Exports.FindAsync(id);
            var rest = export.Customer.RestBoxeses.FirstOrDefault(r => r.BoxTypeId == export.BoxTypeId);
            if (rest != null)
            {
                rest.Count -= export.Quantity;
            }
            db.Exports.Remove(export);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult RestBoxesForPeriod()
        {
            ViewBag.BoxTypeId = new SelectList(db.BoxTypes, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RestBoxesForPeriod(int BoxTypeId)
        {
            var box = db.BoxTypes.Include(b => b.Imports).FirstOrDefault(b => b.Id == BoxTypeId);
            List<RestBoxes> result;
            if (box != null)
            {
                result = box.RestBoxeses.ToList();
            }
            else
            {
                result = db.RestBoxeses.ToList();
            }
            return PartialView("_RestBoxes", result);
        }
    }
}

NoorEl7abeebCompanyWebApp/Views/Customers/Create.cshtml
@using System.Security.AccessControl
@model NoorEl7abeebCompanyWebApp.Models.MyModels.Customer

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div class="row">
    <div class="col-md-6 col-md-offset-3 col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">إضافة عميل</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "POST",OnSuccess = "OnSuccess", OnFailure = "OnFailer" }))
            {
                @Html.AntiForgeryToken()
                <div class="box-body">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    @Html.ActionLink("رجوع", "Index", null, new { @class = "btn btn-default" })
                    <button type="submit" class="btn btn-info pull-right">إضافة</button>
                </div>
            }
        </div>
    </div>
</div>
@section scripts
{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script>
        function OnSuccess(data) {
            Swal.fire({
                type: 'success',
                title: 'تم إضافةالعميل / ' + data.Name +' بنجاح',
                showConfirmButton: true,

            })
        }
        function OnFailer(err) {

            Swal.fire({
                type: 'danger',
                title: err,
                showConfirmButton: true,

            })
        }
    </script>>
}

NoorEl7abeebCompanyWebApp/Views/Customers/Delete.cshtml
@model NoorEl7abeebCompanyWebApp.Models.MyModels.Customer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NoorEl7abeebCompanyWebApp/Views/Customers/Details.cshtml
@model NoorEl7abeebCompanyWebApp.Models.MyModels.Customer
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section Styles {
    @Styles.Render("~/Content/AdminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css")
    
}
@{
    var imports = Model.Imports.GroupBy(i => i.BoxType.Name).Select(i => new { BoxTypeName = i.Key, Count = i.Sum(ii => ii.Quantity) });
    var rests = Model.RestBoxeses.ToList();

}

<div class="row">
    
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border bg-info text-center">
                <h1 class="box-title">@Model.Name</h1>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                @*<ul class="nav nav-pills bg-success">
                        <li role="presentation">@Html.ActionLink("إضافة كمية", "Create", "Imports", new { userId = Model.Id }, null)</li>
                        <li role="presentation">@Html.ActionLink("إضافة صناديق", "Create", "Exports", new { userId = Model.Id }, null)</li>
                        <li role="presentation">@Html.ActionLink("إرجاع صناديق", "Create", "Imports", new { userId = Model.Id }, null)</li>
                        <li role="presentation">@Html.ActionLink("دفع مبلغ", "Create", "Payments", new { userId = Model.Id }, null)</li>
                        <li role="presentation">@Html.ActionLink("المدفوعات", "Create", "Imports", new { userId = Model.Id }, null)</li>
                        <li role="presentation">@Html.ActionLink("الصادرات", "Create", "Imports", new { userId = Model.Id }, null)</li>
                        <li role="presentation">@Html.ActionLink("الواردات", "Create", "Imports", new { userId = Model.Id }, null)</li>
                    </ul>*@
                <div class="row">
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-aqua"><i class="fa fa-envelope-o"></i></span>
                            <div class="info-box-content">
                                <span class="info-box-text"><b>المبلغ المدفوع</b></span>
                                <span class="info-box-number">@Model.Payments.Sum(p => p.Money)</span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-green"><i class="fa fa-flag-o"></i></span>
                            <div class="info-box-content">
                                <span class="info-box-text"><b>المبلغ المتبقى</b></span>
                                <span class="info-box-number">@(Model.Imports.Sum(i => i.TotalPrice) - Model.Payments.Sum(p => p.Money))</span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-yellow"><i class="fa fa-files-o"></i></span>
                            <div class="info-box-content">
                                <span class="info-box-text"><b>الواردات</b></span>
                                @foreach (var item in imports)
                                {
                                    <span class="info-box-text">@item.BoxTypeName : @item.Count</span>
                                }

                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="info-box">
                            <span class="info-box-icon bg-red"><i class="fa fa-star-o"></i></span>
                            <div class="info-box-content">
                                <span class="info-box-text"><b>الصناديق الفارغة المتبقية</b></span>
                                @foreach (var item in rests)
                                {
                                    <span class="info-box-text">@item.BoxType.Name : @item.Count</span>
                                }
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                </div>
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#imports" data-toggle="tab">الواردات</a></li>
                        <li><a href="#exports" data-toggle="tab">الصادرات</a></li>
                        <li><a href="#payments" data-toggle="tab">المدفوعات</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="active tab-pane" id="imports">
                            @Html.ActionLink("إضافة كمية", "Create", "Imports", new { customerId = Model.Id }, new { @class = "btn btn-primary" ,style="margin:20px" })
                            @Html.Partial("_CustomerImports", Model.Imports)
                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="exports">
                            @Html.ActionLink("أضافة صناديق فارغة", "Create", "Exports", new { customerId = Model.Id }, new { @class = "btn btn-primary", style = "margin:20px" })
                            @Html.ActionLink("إرجاع صناديق فارغة", "ReturnEmptyBoxes", "Exports", new { customerId = Model.Id }, new { @class = "btn btn-success", style = "margin:20px" })
                            @Html.Partial("_CustomerExports", Model.Exports)
                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="payments">
                            @Html.ActionLink("دفع مبلغ", "Create", "Payments", new { customerId = Model.Id }, new { @class = "btn btn-primary", style = "margin:20px" })
                            @Html.Partial("_CustomerPayments", Model.Payments)
                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                </div>
                
            </div>

            <!-- /.box-body -->
            <div class="box-footer">
                @Html.ActionLink("رجوع", "Index", null, new { @class = "btn btn-default" })
                @*<button type="submit" class="btn btn-info pull-right">تسجيل</button>*@
            </div>

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/Content/AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js")
    @Scripts.Render("~/Scripts/plugin.js")
}

NoorEl7abeebCompanyWebApp/Views/Customers/Index.cshtml
@model IEnumerable<NoorEl7abeebCompanyWebApp.Models.MyModels.Customer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section Styles {
    @Styles.Render("~/Content/AdminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css")
}
<p>
    @Html.ActionLink("إضافة عميل جديد", "Create",null,new { @class="btn btn-primary"})
</p>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">العمـــــــلاء</h3>
                    <button class="btn btn-primary" onclick="printFunc()">Print</button>
                </div>
                <!-- /.box-header -->
                <div id="printarea" class="box-body">
                    <table id="customers" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th class="noPrint"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.ActionLink(item.Name, "Details", "Customers", new { id = item.Id }, null)
                                    </td>
                                    <td class="noPrint">
                                        @Html.ActionLink("تعديل", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                                        @Html.ActionLink("تفاصيل", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) 
                                        @*@Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
@section Scripts {
    @Scripts.Render("~/Content/AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js")
    @Scripts.Render("~/Content/AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js")
    @Scripts.Render("~/Scripts/plugin.js")
    <script>
    function printFunc() {
        var divToPrint = document.getElementById('customers');
        style = "\
        @@media print{\
            * {\
                -webkit-box-sizing: border-box;\
                -moz-box-sizing: border-box;\
                box-sizing: border-box;\
            }\
    a{\
    color:#000;text-decoration:none;}\
    \
            body {\
                border: 1px #000000 double;\
                margin: 5px;\
                padding: 10px;\
                direction: rtl;\
            }\
    \
            table {\
                border-collapse: collapse;\
                border: #000 solid 1px;\
                font-family: Tahoma, Geneva, sans-serif;\
                width: 80%;\
                margin: auto;\
            }\
    \
            table th {\
                background-color: #333;\
                color: #ffffff;\
                font-weight: bold;\
                padding: 15px;\
            }\
    \
            table td { padding: 15px; }\
    \
            table thead td {\
                background-color: #54585d;\
                color: #ffffff;\
                font-weight: bold;\
                font-size: 13px;\
                border: 1px solid #54585d;\
            }\
            \
            table tbody td {\
                color: #636363;\
                border: 1px solid #dddfe1;\
            }\
            \
            table tbody tr { background-color: #f9fafb; }\
            \
            table tbody tr:nth-child(odd) { background-color: #ffffff; }\
            \
            .companyName {\
                padding: 20px;\
                font-size: xx-large;\
                font-weight: bold;\
                text-align: center;\
                width: 100%;\
                font-family: Tahoma, Geneva, sans-serif;\
            }\
            \
            .documentTitle {\
                padding: 10px;\
                background-color: #eee;\
                font-size: medium;\
                font-weight: bold;\
                text-align: center;\
                width: 100%;\
                font-family: Tahoma, Geneva, sans-serif;\
            }\
            \
            .noPrint { display: none; }\
        }";
        htmlToPrint = divToPrint.outerHTML;

        newWin = window.open("");
        newWin.document.write(
            '<html><head><link href="../../Content/PrintStyle.css" media="print" rel="stylesheet" /></head><body>');
        newWin.document.write("<h1 class='companyName'>شركـــة نــــــور الحبيــــب</h1>");
        newWin.document.write("<h3 class='documentTitle'>تقرير بأسماء عملاء الشركة</h3>");
        newWin.document.write("<style>" + style + "</style>");
        newWin.document.write(htmlToPrint);
        newWin.document.write("</body></html>");

        newWin.print();
        newWin.close();
        }
    </script>
}